### ISSUE TITLE
Fails to build on Raspbian GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by coreybruce** [snesrev/zelda3#254]
### Describe your bug here. And how to reproduce it.

```
make -j2
cc zelda_rtl.o util.o zelda_cpu_infra.o config.o sprite_main.o tile_detect.o dungeon.o poly.o overworld.o nmi.o glsl_shader.o select_file.o overlord.o opengl.o player_oam.o audio.o load_gfx.o ending.o spc_player.o attract.o hud.o player.o misc.o messaging.o sprite.o ancilla.o main.o tagalong.o snes/dsp.o snes/spc.o snes/ppu.o snes/snes_other.o snes/cart.o snes/snes.o snes/cpu.o snes/apu.o snes/dma.o snes/input.o snes/tracing.o third_party/gl_core/gl_core_3_1.o third_party/opus-1.3.1-stripped/opus_decoder_amalgam.o -o zelda3  -L/usr/lib/arm-linux-gnueabihf -lSDL2 -lm
Extracting game resources
Traceback (most recent call last):
  File "restool.py", line 35, in <module>
    import extract_resources
  File "/home/pi/zelda3/tables/extract_resources.py", line 3, in <module>
    import text_compression
  File "/home/pi/zelda3/tables/text_compression.py", line 472
    if r := rev.get(a[0]):
          ^
SyntaxError: invalid syntax
make: *** [Makefile:31: tables/zelda3_assets.dat] Error 1
make: *** Waiting for unfinished jobs....
```

### What is your build target?

Linux

**Comment by qurious-pixel** [comment]
see https://github.com/snesrev/zelda3/issues/249

Requires minimum `Python 3.8`

**Comment by coreybruce** [comment]
Ahh right I see, no problem. Thanks for letting me know. 🙂
