### ISSUE TITLE
Constatly getting "Could not find a part of the path" Errors when building

### ISSUE THREAD

**Issue by Nexxus88** [snesrev/zelda3#288]
### Describe your bug here. And how to reproduce it.

Using a US rom renamed to zelda3.sfc with a matching hash I get this error everytime, I have placed the zelda 3 rom in the same directory as the launcher. Running an up to date modern windows 11 machine and yeah just errors every time I attempt it.

Details states

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Zelda_3_Launcher.progressForm.copyROM(Object sender, EventArgs e) in C:\Users\Anthony\source\repos\Zelda 3 Launcher\Zelda 3 Launcher\progressForm.Designer.cs:line 72
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

### What is your build target?

Windows

**Comment by impeeza** [comment]
Try removing spaces from the folder name and full path.
